# Generated by Django 4.2 on 2025-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='start_date',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='title',
            field=models.CharField(default='Default Goal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
